export const translations = {
    en: {
        title: "Marriage Biodata",
        invocation: "|| Shree Ganeshay Namah ||",
        labels: {
            details: "Biodata Details",
            add_field: "+ Add Field",
            generate: "Download PDF",
            name: "Full Name",
            photo: "Profile Photo",
            age: "Age",
            height: "Height",
            date_of_birth: "Date of Birth",
            place_of_birth: "Place of Birth",
            caste: "Caste",
            phone: "Phone",
            education: "Education",
            occupation: "Occupation",
            income: "Income",
            "father's_occupation": "Father's Occupation",
            "mother's_occupation": "Mother's Occupation",
            siblings: "Siblings",
            address: "Address",
            hobbies: "Hobbies"
        }
    },
    hi: {
        title: "विवाह बायोडाटा",
        invocation: "|| श्री गणेशाय नमः ||",
        labels: {
            details: "बायोडाटा विवरण",
            add_field: "+ फ़ील्ड जोड़ें",
            generate: "डाउनलोड",
            name: "पूरा नाम",
            photo: "फ़ोटो",
            age: "आयु",
            height: "कद",
            date_of_birth: "जन्म तिथि",
            place_of_birth: "जन्म स्थान",
            caste: "जाति",
            phone: "फ़ोन",
            education: "शिक्षा",
            occupation: "व्यवसाय",
            income: "आय",
            "father's_occupation": "पिता का व्यवसाय",
            "mother's_occupation": "माता का व्यवसाय",
            siblings: "भाई-बहन",
            address: "पता",
            hobbies: "शौक"
        }
    },
    mr: {
        title: "लग्न बायोडाटा",
        invocation: "|| श्री गणेशाय नमः ||",
        labels: {
            details: "बायोडाटा तपशील",
            add_field: "+ नवीन माहिती जोडा",
            generate: "डाउनलोड",
            name: "पूर्ण नाव",
            photo: "फोटो",
            age: "वय",
            height: "उंची",
            date_of_birth: "जन्म तारीख",
            place_of_birth: "जन्म ठिकाण",
            caste: "जात",
            phone: "फोन",
            education: "शिक्षण",
            occupation: "व्यवसाय",
            income: "उत्पन्न",
            "father's_occupation": "वडिलांचा व्यवसाय",
            "mother's_occupation": "आईचा व्यवसाय",
            siblings: "भावंडे",
            address: "पत्ता",
            hobbies: "छंद"
        }
    },
    ta: {
        title: "திருமண பயோடேட்டா",
        invocation: "|| ஓம் கணேசாய நமஹ ||",
        labels: {
            details: "விவரங்கள்",
            add_field: "+ விவரத்தைச் சேர்",
            generate: "பதிவிறக்கம்",
            name: "முழு பெயர்",
            photo: "படம்",
            age: "வயது",
            height: "உயரம்",
            date_of_birth: "பிறந்த தேதி",
            place_of_birth: "பிறந்த இடம்",
            caste: "சாதி",
            phone: "தொலைபேசி",
            education: "கல்வி",
            occupation: "வேலை",
            income: "வருமானம்",
            "father's_occupation": "தந்தையின் வேலை",
            "mother's_occupation": "தாயின் வேலை",
            siblings: "உடன்பிறப்புகள்",
            address: "முகவரி",
            hobbies: "பொழுதுபோக்கு"
        }
    },
    ml: {
        title: "വിവാഹ ബയോഡാറ്റ",
        invocation: "|| ശ്രീ ഗണേശായ നമഃ ||",
        labels: {
            details: "വിവരങ്ങൾ",
            add_field: "+ ചേർക്കുക",
            generate: "ഡൗൺലോഡ്",
            name: "മുഴുവൻ പേര്",
            photo: "ഫോട്ടോ",
            age: "പ്രായം",
            height: "ഉയരം",
            date_of_birth: "ജന്മ തീയതി",
            place_of_birth: "ജനന സ്ഥലം",
            caste: "ജാതി",
            phone: "ഫോൺ",
            education: "വിദ്യാഭ്യാസം",
            occupation: "ജോലി",
            income: "വരുമാനം",
            "father's_occupation": "പിതാവിന്റെ ജോലി",
            "mother's_occupation": "മാതാവിന്റെ ജോലി",
            siblings: "സഹോദരങ്ങൾ",
            address: "വിലാസം",
            hobbies: "താൽപ്പര്യങ്ങൾ"
        }
    },
    bh: {
        title: "शादी के बायोडाटा",
        invocation: "|| श्री गणेशाय नमः ||",
        labels: {
            details: "जानकारी",
            add_field: "+ अउरी जोड़ें",
            generate: "डाउनलोड",
            name: "पूरा नाम",
            photo: "फोटो",
            age: "उमिर",
            height: "लंबाई",
            date_of_birth: "जनम तिथि",
            place_of_birth: "जनम जगह",
            caste: "जाति",
            phone: "मोबाइल नंबर",
            education: "पढ़ाई",
            occupation: "काम",
            income: "कमाई",
            "father's_occupation": "बाबूजी के काम",
            "mother's_occupation": "माई के काम",
            siblings: "भाई-बहिन",
            address: "पता",
            hobbies: "शौक"
        }
    }
};
