export const translations = {
    en: {
        title: "Marriage Biodata",
        invocation: "|| Shree Ganeshay Namah ||",
        labels: {
            details: "Biodata Details",
            add_field: "+ Add Field",
            generate: "Download PDF",
            name: "Full Name",
            photo: "Profile Photo",
            age: "Age",
            height: "Height",
            date_of_birth: "Date of Birth",
            place_of_birth: "Place of Birth",
            caste: "Caste",
            phone: "Phone",
            education: "Education",
            occupation: "Occupation",
            income: "Income",
            "father's_occupation": "Father's Occupation",
            "mother's_occupation": "Mother's Occupation",
            siblings: "Siblings",
            address: "Address",
            hobbies: "Hobbies"
        }
    },
    hi: {
        title: "विवाह बायोडाटा",
        invocation: "|| श्री गणेशाय नमः ||",
        labels: {
            details: "बायोडाटा विवरण",
            add_field: "+ फ़ील्ड जोड़ें",
            generate: "डाउनलोड",
            name: "पूरा नाम",
            photo: "फ़ोटो",
            age: "आयु",
            height: "कद",
            date_of_birth: "जन्म तिथि",
            place_of_birth: "जन्म स्थान",
            caste: "जाति",
            phone: "फ़ोन",
            education: "शिक्षा",
            occupation: "व्यवसाय",
            income: "आय",
            "father's_occupation": "पिता का व्यवसाय",
            "mother's_occupation": "माता का व्यवसाय",
            siblings: "भाई-बहन",
            address: "पता",
            hobbies: "शौक"
        }
    },
    mr: {
        title: "लग्न बायोडाटा",
        invocation: "|| श्री गणेशाय नमः ||",
        labels: {
            details: "बायोडाटा तपशील",
            add_field: "+ नवीन माहिती जोडा",
            generate: "डाउनलोड",
            name: "पूर्ण नाव",
            photo: "फोटो",
            age: "वय",
            height: "उंची",
            date_of_birth: "जन्म तारीख",
            place_of_birth: "जन्म ठिकाण",
            caste: "जात",
            phone: "फोन",
            education: "शिक्षण",
            occupation: "व्यवसाय",
            income: "उत्पन्न",
            "father's_occupation": "वडिलांचा व्यवसाय",
            "mother's_occupation": "आईचा व्यवसाय",
            siblings: "भावंडे",
            address: "पत्ता",
            hobbies: "छंद"
        }
    },
    ta: {
        title: "திருமண பயோடேட்டா",
        invocation: "|| ஓம் கணேசாய நமஹ ||",
        labels: {
            details: "விவரங்கள்",
            add_field: "+ விவரத்தைச் சேர்",
            generate: "பதிவிறக்கம்",
            name: "முழு பெயர்",
            photo: "படம்",
            age: "வயது",
            height: "உயரம்",
            date_of_birth: "பிறந்த தேதி",
            place_of_birth: "பிறந்த இடம்",
            caste: "சாதி",
            phone: "தொலைபேசி",
            education: "கல்வி",
            occupation: "வேலை",
            income: "வருமானம்",
            "father's_occupation": "தந்தையின் வேலை",
            "mother's_occupation": "தாயின் வேலை",
            siblings: "உடன்பிறப்புகள்",
            address: "முகவரி",
            hobbies: "பொழுதுபோக்கு"
        }
    },
    ml: {
        title: "വിവാഹ ബയോഡാറ്റ",
        invocation: "|| ശ്രീ ഗണേശായ നമഃ ||",
        labels: {
            details: "വിവരങ്ങൾ",
            add_field: "+ ചേർക്കുക",
            generate: "ഡൗൺലോഡ്",
            name: "മുഴുവൻ പേര്",
            photo: "ഫോട്ടോ",
            age: "പ്രായം",
            height: "ഉയരം",
            date_of_birth: "ജന്മ തീയതി",
            place_of_birth: "ജനന സ്ഥലം",
            caste: "ജാതി",
            phone: "ഫോൺ",
            education: "വിദ്യാഭ്യാസം",
            occupation: "ജോലി",
            income: "വരുമാനം",
            "father's_occupation": "പിതാവിന്റെ ജോലി",
            "mother's_occupation": "മാതാവിന്റെ ജോലി",
            siblings: "സഹോദരങ്ങൾ",
            address: "വിലാസം",
            hobbies: "താൽപ്പര്യങ്ങൾ"
        }
    },
    bh: {
        title: "शादी के बायोडाटा",
        invocation: "|| श्री गणेशाय नमः ||",
        labels: {
            details: "जानकारी",
            add_field: "+ अउरी जोड़ें",
            generate: "डाउनलोड",
            name: "पूरा नाम",
            photo: "फोटो",
            age: "उमिर",
            height: "लंबाई",
            date_of_birth: "जनम तिथि",
            place_of_birth: "जनम जगह",
            caste: "जाति",
            phone: "मोबाइल नंबर",
            education: "पढ़ाई",
            occupation: "काम",
            income: "कमाई",
            "father's_occupation": "बाबूजी के काम",
            "mother's_occupation": "माई के काम",
            siblings: "भाई-बहिन",
            address: "पता",
            hobbies: "शौक"
        }
    },
    ur: {
        title: "شادی کا بائیو ڈیٹا",
        invocation: "|| بسم اللہ الرحمن الرحیم ||",
        labels: {
            details: "بائیو ڈیٹا کی تفصیلات",
            add_field: "+ فیلڈ شامل کریں",
            generate: "ڈاؤن لوڈ",
            name: "مکمل نام",
            photo: "تصویر",
            age: "عمر",
            height: "قد",
            date_of_birth: "تاریخ پیدائش",
            place_of_birth: "جائے پیدائش",
            caste: "ذات/برادری",
            phone: "فون نمبر",
            education: "تعلیم",
            occupation: "پیشہ",
            income: "آمدنی",
            "father's_occupation": "والد کا پیشہ",
            "mother's_occupation": "والدہ کا پیشہ",
            siblings: "بہن بھائی",
            address: "پتہ",
            hobbies: "مشاغل"
        }
    },
    pa: {
        title: "ਵਿਆਹ ਦਾ ਬਾਇਓਡਾਟਾ",
        invocation: "|| ੴ ਸਤਿਗੁਰ ਪ੍ਰਸਾਦਿ ||",
        labels: {
            details: "ਬਾਇਓਡਾਟਾ ਜਾਣਕਾਰੀ",
            add_field: "+ ਨਵੀਂ ਜਾਣਕਾਰੀ ਜੋੜੋ",
            generate: "ਡਾਊਨਲੋਡ",
            name: "ਪੂਰਾ ਨਾਮ",
            photo: "ਫੋਟੋ",
            age: "ਉਮਰ",
            height: "ਕੱਦ",
            date_of_birth: "ਜਨਮ ਮਿਤੀ",
            place_of_birth: "ਜਨਮ ਸਥਾਨ",
            caste: "ਜਾਤ",
            phone: "ਫੋਨ ਨੰਬਰ",
            education: "ਵਿੱਦਿਆ",
            occupation: "ਕੰਮਕਾਰ",
            income: "ਆਮਦਨ",
            "father's_occupation": "ਪਿਤਾ ਦਾ ਕੰਮਕਾਰ",
            "mother's_occupation": "ਮਾਤਾ ਦਾ ਕੰਮਕਾਰ",
            siblings: "ਭੈਣ-ਭਰਾ",
            address: "ਪਤਾ",
            hobbies: "ਸ਼ੌਂਕ"
        }
    },
    te: {
        title: "వివాహ బయోడేటా",
        invocation: "|| శ్రీ గణేశాయ నమః ||",
        labels: {
            details: "బయోడేటా వివరాలు",
            add_field: "+ అదనపు సమాచారం",
            generate: "డౌన్‌లోడ్",
            name: "పూర్తి పేరు",
            photo: "ఫోటో",
            age: "వయస్సు",
            height: "ఎత్తు",
            date_of_birth: "పుట్టిన తేదీ",
            place_of_birth: "పుట్టిన స్థలం",
            caste: "కులం",
            phone: "ఫోన్ సంఖ్య",
            education: "చదువు",
            occupation: "ఉద్యోగం/వృత్తి",
            income: "ఆదాయం",
            "father's_occupation": "తండ్రి వృత్తి",
            "mother's_occupation": "తల్లి వృత్తి",
            siblings: "తోబుట్టువులు",
            address: "చిరునామా",
            hobbies: "అభిరుచులు"
        }
    },
    kn: {
        title: "ಮದುವೆಯ ಬಯೋಡೇಟಾ",
        invocation: "|| ಶ್ರೀ ಗಣೇಶಾಯ ನಮಃ ||",
        labels: {
            details: "ಬಯೋಡೇಟಾ ವಿವರಗಳು",
            add_field: "+ ಹೊಸ ಮಾಹಿತಿ ಸೇರಿಸಿ",
            generate: "ಡೌನ್‌ಲೋಡ್",
            name: "ಪೂರ್ಣ ಹೆಸರು",
            photo: "ಫೋಟೋ",
            age: "ವಯಸ್ಸು",
            height: "ಎತ್ತರ",
            date_of_birth: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
            place_of_birth: "ಹುಟ್ಟಿದ ಸ್ಥಳ",
            caste: "ಜಾತಿ",
            phone: "ಫೋನ್ ಸಂಖ್ಯೆ",
            education: "ವಿದ್ಯಾಭ್ಯಾಸ",
            occupation: "ಉದ್ಯೋಗ",
            income: "ಆದಾಯ",
            "father's_occupation": "ತಂದೆಯ ಉದ್ಯೋಗ",
            "mother's_occupation": "ತಾಯಿಯ ಉದ್ಯೋಗ",
            siblings: "ಸಹೋದರ ಸಹೋದರಿಯರು",
            address: "ವಿಳಾಸ",
            hobbies: "ಅಭಿರುಚಿಗಳು"
        }
    }
};
